# Site
name: 'Drew Wilson'
description: 'Random stuff from Drew Wilson. Youtuber who makes cringe content.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'Drew Wilson'
email: ''
mailchimp-list: 'https://club.us10.list-manage.com/subscribe/post?u=b3ff55e61cd524ebabe1d6674&amp;id=666c3a8a18'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    drew:
      name:           Drew Wilson
      site:           https://www.drewwilson.club
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Drew Wilson, the author of my blog. I hope you like it!"
      email:          
      twitter:        
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Drew Wilson
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
